services:
  agentcoin-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./var:/app/var
      - ./configs:/app/configs
    environment:
      PYTHONUNBUFFERED: "1"

